#pragma once

#include <string>

#define ENGINE_VERSION_MAJOR 0
#define ENGINE_VERSION_MINOR 10
#define ENGINE_VERSION_PATCH 2
#define ENGINE_VERSION_BUILD 1

#define ENGINE_VERSION_DIVIDER "."

#define ENGINE_VERSION std::to_string(ENGINE_VERSION_MAJOR) + ENGINE_VERSION_DIVIDER + std::to_string(ENGINE_VERSION_MINOR) + ENGINE_VERSION_DIVIDER + std::to_string(ENGINE_VERSION_PATCH) + ENGINE_VERSION_DIVIDER + std::to_string(ENGINE_VERSION_BUILD)